# Generated by Django 4.0.3 on 2022-04-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_alter_category_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='expenseincome',
            name='budget_id',
        ),
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.CharField(default='Descritption', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetuser',
            name='role',
            field=models.IntegerField(),
        ),
    ]
