# Generated by Django 4.0.3 on 2022-04-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_remove_budget_end_date_remove_budget_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget'),
        ),
    ]
