# Generated by Django 4.0.3 on 2022-04-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_alter_category_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.budget'),
        ),
    ]
